server:
 port: 8191
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RubendarDeenadayalan/Spring-config-server
          search-paths:
          - '*service'
    
